# Docker Compose para Producción
# Optimizado con Nginx + PHP-FPM

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: production
    container_name: mini-trello-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - mini-trello-network

  nginx:
    image: nginx:alpine
    container_name: mini-trello-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mini-trello-network

  redis:
    image: redis:7-alpine
    container_name: mini-trello-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mini-trello-network

networks:
  mini-trello-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
